### ISSUE TITLE
Parse exception when cueing a role vector script within a boolean expression

### ISSUE THREAD

**Issue by hvaldecantos** [jcoplien/trygve#102]
Trygve fails to parse the following code:

``` trygve
context Context {
    role [] Word {
        public String character() { return toString(); }
        public int number() { return index; }
    } requires {
        String toString();
    }

    public Context(String aString) {
        Word = aString.split("");
    }
    public void test() {
        System.out.println(Word[0].character() == "0");
        if(Word[1].character == "1") System.out.println("one");
        System.out.println(Word[2].number() > Word[3].number());
    }   
}
{
    new Context("0123456789").test();
}

/* GOLD:
___________________________________________________________
true
one
false
*/
```

Compiler message:

```
Compilation complete
Exception in thread "main" java.lang.NullPointerException
    at info.fulloo.trygve.parser.Pass1Listener.exitBoolean_expr(Pass1Listener.java:2554)
    at info.fulloo.trygve.parser.KantParser$Boolean_exprContext.exitRule(KantParser.java:4146)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at info.fulloo.trygve.parser.ParseRun.pass1(ParseRun.java:96)
    at info.fulloo.trygve.parser.ParseRun.commonInit(ParseRun.java:73)
    at info.fulloo.trygve.parser.ParseRun$BatchParseRun.<init>(ParseRun.java:148)
    at info.fulloo.trygve.editor.BatchRunner.processBatch(BatchRunner.java:42)
    at info.fulloo.trygve.editor.Main.main(Main.java:34

```

Using trygve 1.6.17

**Comment by jcoplien** [comment]
This one gave me some entertainment…;-)

The main bug was a result of some not-quite-right changes in the new error propagation logic. Should be fixed in the latest push.

But there is another bug, and I don’t know if it was intentional or an oversight, but your code fails to include the perfunctory “()” on the second call to the character method. What’s odd is that the new error-message-trimming actually let that through but it of course ultimately led to an internal error. Something I have been wanting to do for a long time is to allow Eiffel-style “features” instead of distinguishing between methods and data member access syntax. So I finally bit the bullet and, at least for this case, have done it.

The other thing I’d like is to forego the curly braces on method definitions but I think I’m stuck with that...

Fascinating little example you wrote, btw.

**Comment by hvaldecantos** [comment]
It was unintentional, I occasionally forget parentheses. Errors are good source of information. You are right, the next code runs:

``` trygve
context Context {
    ...
}
{
    int i = Word[1].character;
    System.out.println(i);
}
```

It prints `<null>`.

> Something I have been wanting to do for a long time is to allow Eiffel-style “features” instead of distinguishing between methods and data member access syntax. So I finally bit the bullet and, at least for this case, have done it. 
> The other thing I’d like is to forego the curly braces on method definitions but I think I’m stuck with that... 

I haven't written or read any Eiffel code, I just looked something up in Wikipedia, it looks interesting. It is going to be  interesting too to see how trygve language departs from java syntax, conceptually we are far enough.

> Fascinating little example you wrote, btw.

Thank you.

**Comment by jcoplien** [comment]
> Den 27/03/2016 kl. 23.15 skrev Héctor Adrián Valdecantos notifications@github.com:
> 
> context Context {
>     ...
> }
> {
>     int i = Word[1].character;
>     System.out.println(i);
> }
> Huh? Can I see the whole thing?

Your original example now prints:

true
one
false

**Comment by hvaldecantos** [comment]
Yes, the original example (with and without the parenthesis) with the last push prints: 

```
true
one
false
```

Regarding the modified version (only the `test` script):

```
context Context {
    role [] Word {
        public String character() { return toString(); }
        public int number() { return index; }
    } requires {
        String toString();
    }

    public Context(String aString) {
        Word = aString.split("");
    }
    public void test() {
        int i = Word[1].character;
        System.out.println(i);
    }   
}
{
    new Context("0123456789").test();
}
```

I wasn't using the latest push, it used to compile, but now I get

```
line 13: Type mismatch in initialization of `i'.
```

Is that the desired behavior?

**Comment by hvaldecantos** [comment]
Sorry,  the intended modification was:

```
context Context {
    role [] Word {
        public String character() { return toString(); }
        public int number() { return index; }
    } requires {
        String toString();
    }

    public Context(String aString) {
        Word = aString.split("");
    }
    public void test() {
        int i = Word[1].number;
        System.out.println(i);
    }   
}
{
    new Context("0123456789").test();
}
```

It works great:

```
Compilation complete
1
```

**Comment by jcoplien** [comment]
> Den 27/03/2016 kl. 23.41 skrev Héctor Adrián Valdecantos <notifications@github.com <mailto:notifications@github.com>>:
> 
> I wasn't using the latest push, it used to compile, but now I get
> 
> line 13: Type mismatch in initialization of `i'.
> Is that the desired behavior?
> 
> Yup.

**Comment by jcoplien** [comment]
Thanks, Héctor!

**Comment by hvaldecantos** [comment]
There seems to be a remnant bug hanging around parentheses:

```
context Context {
    role [] RoleVector {
        public boolean returns_true() { return true; }
    }
    public Context(String aString) {
        RoleVector = aString.split("");
    }
    public void test() {
        if(RoleVector[0].returns_true) System.out.println("TRUE");           // parse ok
        if(RoleVector[0].returns_true()) System.out.println("TRUE");         // not parsing
    }   
}
{
    new Context("0123456789").test();
}

/* GOLD:
___________________________________________________________
TRUE
TRUE
*/
```

Using trygve 1.6.17

**Comment by hvaldecantos** [comment]
The parse issue is still there. Parsing a role vector script enactment using parentheses is still failing:

```
Compilation complete
Exception in thread "main" java.lang.NullPointerException
    at info.fulloo.trygve.parser.Pass1Listener.exitIf_expr(Pass1Listener.java:3446)
    at info.fulloo.trygve.parser.KantParser$If_exprContext.exitRule(KantParser.java:4735)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at info.fulloo.trygve.parser.ParseRun.pass1(ParseRun.java:96)
    at info.fulloo.trygve.parser.ParseRun.commonInit(ParseRun.java:73)
    at info.fulloo.trygve.parser.ParseRun$BatchParseRun.<init>(ParseRun.java:148)
    at info.fulloo.trygve.editor.BatchRunner.processBatch(BatchRunner.java:42)
    at info.fulloo.trygve.editor.Main.main(Main.java:34)
```

I've also tried passing parameters within the parentheses and I get the same results:

``` trygve
context Context {
    role [] RoleVector {
        public boolean is_the_string(String s) { return s == toString() }
    } requires {
        String toString() const;
    }
    public Context(String aString) {
        RoleVector = aString.split("");
    }
    public void test() {
        if(RoleVector[0].is_the_string("0")) System.out.println("TRUE");
        if(RoleVector[4].is_the_string("4")) System.out.println("TRUE");
    }   
}
{
    new Context("0123456789").test();
}

/* GOLD:
___________________________________________________________
TRUE
TRUE
*/
```

Using trygve version 2.0.4

**Comment by hvaldecantos** [comment]
It works, thanks!

**Comment by jcoplien** [comment]
Thanks, Héctor!
