### ISSUE TITLE
stageprop vectors fail to bind role-player members of a list.

### ISSUE THREAD

**Issue by hvaldecantos** [jcoplien/trygve#103]
The following code doesn't compile:

``` trygve
context C {
    public C(List<String> ls) {
        RoleVector = ls;
    }
    stageprop [] RoleVector {
        public void prints_elements() {
            System.out.println(toString());
            if(index < lastIndex) RoleVector[index + 1].prints_elements
        }
    } requires {
        public String toString() const;
    }
    public void run() {
        RoleVector[0].prints_elements
    }
}
{
    List<String> ss = new List<String>();
    ss.add("Hello")
    ss.add("World")
    new C(ss).run()
}
```

The compiler is not able to assign each `String` object a stageprop role RoleVector:

``` output
line 3: Role `RoleVector' cannot be played by object of type `List<String>':
line 3:     `toString()' needed by Stage Prop `RoleVector' does not appear in interface of `List<String>'.
Compilation complete
2 fatal errors
```

---

When using a array of `String`s the code compiles but trygve raises a runtime exception:

``` output
context C {
    public C(String [] ls) {
        RoleVector = ls;
    }
    stageprop [] RoleVector {
        public void prints_elements() {
            System.out.println(toString());
            if(index < lastIndex) RoleVector[index + 1].prints_elements
        }
    } requires {
        public String toString() const;
    }
    public void run() {
        RoleVector[0].prints_elements
    }
}
{
    new C("Hello World".split(" ")).run()
}
```

```
Compilation complete
Hello
Exception in thread "main" java.lang.AssertionError
    at info.fulloo.trygve.run_time.RTExpression$RTRoleArrayIndexExpression.run(RTExpression.java:2665)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:391)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.pushArgumentLoop(RTMessageDispatcher.java:250)
    at info.fulloo.trygve.run_time.RTMessageDispatcher$RTRoleToRole.<init>(RTMessageDispatcher.java:1278)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.makeDispatcher(RTMessageDispatcher.java:116)
    at info.fulloo.trygve.run_time.RTExpression$RTMessage.run(RTExpression.java:707)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:391)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.run(RunTimeEnvironment.java:172)
    at info.fulloo.trygve.editor.BatchRunner.simpleRun(BatchRunner.java:61)
    at info.fulloo.trygve.editor.BatchRunner.processBatch(BatchRunner.java:49)
    at info.fulloo.trygve.editor.Main.main(Main.java:34)
```

Using trygve 1.6.18

**Comment by hvaldecantos** [comment]
Thanks James.

**Comment by jcoplien** [comment]
Thanks, Héctor!
