### ISSUE TITLE
Assertion error when class is undeclared

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#113]
Hi Cope,
This is another silly mistake due to copying and pasting incorrectly as I was reworking my code, but I thought you might want to know about the AssertionError. I accidentally omitted the Activity class with the following code and got the exception below (in addition to some compile errors which appear to be correct).

```
context FrontloadActivities
{
    private Project project_;

    public FrontloadActivities(Project proj) {
        project_ = proj;
        Activities = proj.activities();
    }

    public void frontload() {
        Activities.resetStartTimes();
        List<Activity> unplannedActivities;
        do {
            unplannedActivities = Activities.findUnplanned();
            for (Activity activity: unplannedActivities) {
                //Check to see if early start time has been set.
                //(If the activity has already been planned, then early start time will already be set.)
                if (activity.earlyStartTime() == null) {
                    new FrontloadActivities_PlanActivity(activity)
                        .tryToPlan(project_.startTime());
                }
            }
        }
        while (unplannedActivities.size() > 0);
    }

    role Activities {   
        public void resetStartTimes() {
            for (int i = 0; i < Activities.size(); i++) {
                Activities.get(i).setEarlyStartTime(null);
            }
        }

        public List<Activity> findUnplanned() {
            List<Activity> unplanned = new List<Activity>();
            for (int i = 0; i < Activities.size(); i++) {
                if (Activities.get(i).earlyStartTime() == null) {
                    unplanned.add(Activities.get(i));
                }
            }
            return unplanned;
        }
    }
    requires {
        int size();
        Activity get(int i);
    }

    context PlanActivity
    {
        public PlanActivity(Activity activity) {
            UnplannedActivity = activity;
            Predecessors = activity.dependencies();
        }

        public void tryToPlan(int projectStart) {
            if (UnplannedActivity.hasOnlyPlannedPredecessors()) {
                UnplannedActivity.plan(projectStart);
            }
        }

        role Predecessors {
            public int maxEarlyFinishTime(int projectStart) {
                int maxEarlyFinish = projectStart.clone;
                for (int i=0; i < size(); i++) {
                    if (Predecessors.get(i).earlyFinishTime() > maxEarlyFinish) {
                        maxEarlyFinish = Predecessors.get(i).earlyFinishTime();
                    }
                }
                return maxEarlyFinish;
            }
        }
        requires {
            int size();
            Activity get(int i);
        }

        role UnplannedActivity {
            public boolean hasOnlyPlannedPredecessors() {
                for (int i = 0; i < Predecessors.size(); i++) {
                    if (Predecessors.get(i).earlyStartTime() == null) {
                        return false;
                    }
                }
                return true;
            }

            public void plan(int projectStart) {
                setEarlyStartTime(Predecessors.maxEarlyFinishTime(projectStart));
            }
        }
        requires {
            Predecessors dependencies();
            void setEarlyStartTime(int time);
        }
    }
}

///////////////////////////////////////
class Project {
    private int startTime_;
    private List<Activity> activities_;

    public Project(int startTime) {
        startTime_ = startTime.clone;
        activities_ = new List<Activity>();
    }

    public Project(int startTime, List<Activity> activities) {
        startTime_ = startTime.clone;
        activities_ = activities;
    }

    public void addActivity(Activity a) {
        activities_.add(a);
    }

    public void removeActivity(Activity a) {
        activities_.remove(a);
    }

    public int startTime() {
        return startTime_;
    }

    public List<Activity> activities() {
        return activities_;
    }
}

{}


___________________________________________________________
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
    at info.fulloo.trygve.declarations.Type.signatureForMethodSelectorCommon(Type.java:1403)
    at info.fulloo.trygve.declarations.Type.signatureForMethodSelectorInHierarchyIgnoringThis(Type.java:1462)
    at info.fulloo.trygve.declarations.Type$RoleType.canBeConvertedFrom(Type.java:827)
    at info.fulloo.trygve.declarations.Type$RoleType.canBeConvertedFrom(Type.java:804)
    at info.fulloo.trygve.parser.Pass1Listener.assignmentExpr(Pass1Listener.java:5434)
    at info.fulloo.trygve.parser.Pass1Listener.exitAbelian_expr(Pass1Listener.java:2171)
    at info.fulloo.trygve.parser.KantParser$Abelian_exprContext.exitRule(KantParser.java:3613)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at info.fulloo.trygve.parser.ParseRun.pass2(ParseRun.java:100)
    at info.fulloo.trygve.parser.ParseRun.commonInit(ParseRun.java:74)
    at info.fulloo.trygve.parser.ParseRun$GuiParseRun.<init>(ParseRun.java:133)
    at info.fulloo.trygve.editor.TextEditorGUI.parseButtonActionPerformed(TextEditorGUI.java:1122)
    at info.fulloo.trygve.editor.TextEditorGUI$12.actionPerformed(TextEditorGUI.java:563)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6516)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6281)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:699)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:713)
    at java.awt.EventQueue$4.run(EventQueue.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by jcoplien** [comment]
I can't reproduce this. Can you verify whether this appears to be fixed when you run it?

**Comment by mbrowne** [comment]
It's fixed in the latest version. Closing this - thanks.

**Comment by jcoplien** [comment]
Thanks, Matt.
