### ISSUE TITLE
Duck typing - internal trygve error (java.lang.AssertionError)

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#114]
I figured I should follow convention and file a bug report here for the issue I mentioned on the group. This code compiles (should it? I didn't expect it to, but then again I don't fully know how the new duck typing works):

```
context C1 {
    public C1(A a) {
        R = a;
        R.test();
    }

    role R {
        public void test() {
            new C2(R);
        }
        public void bar() {
            System.out.println("bar")
        }
        public void foo();
    }
    requires {
        void foo();
    }
}

context C2 {
    public C2(B b) {
        b.bar();
     }
}

class A {
    public void foo() {}
}

class B {
    public void foo() {}
    public void bar() {}
}

{
    new C1(new A());
}
```

But gives this error at runtime:

```
Error: User process died because of internal trygve error: java.lang.AssertionError
popping stack: type is RTObjectCommon
    In script `B.bar'
    Called from script `C2.C2'
    Called from script `R.test'
    Called from script `C1.C1'

java.lang.AssertionError
    at info.fulloo.trygve.run_time.RTMessageDispatcher.genericPolymorphicMethodLookup(RTMessageDispatcher.java:631)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.genericMethodDeclLookup(RTMessageDispatcher.java:710)
    at info.fulloo.trygve.run_time.RTMessageDispatcher$RTContextToClass.getMethodDecl(RTMessageDispatcher.java:1150)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.commonWrapup(RTMessageDispatcher.java:393)
    at info.fulloo.trygve.run_time.RTMessageDispatcher$RTContextToClass.<init>(RTMessageDispatcher.java:1107)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.makeDispatcher(RTMessageDispatcher.java:148)
    at info.fulloo.trygve.run_time.RTExpression$RTMessage.run(RTExpression.java:718)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:445)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.run(RunTimeEnvironment.java:227)
    at info.fulloo.trygve.editor.TextEditorGUI.simpleRun(TextEditorGUI.java:1002)
    at info.fulloo.trygve.editor.TextEditorGUI$32.doInBackground(TextEditorGUI.java:1069)
    at info.fulloo.trygve.editor.TextEditorGUI$32.doInBackground(TextEditorGUI.java:1062)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at javax.swing.SwingWorker.run(SwingWorker.java:335)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mbrowne** [comment]
This appears to be fixed in the latest version (it now triggers a compile error). Thanks Cope.
