### ISSUE TITLE
Possible issue with role re-binding?

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#138]
I noticed that there was some dead code in the Dijkstra example, so I started what I thought would be a simple PR to remove it:

https://github.com/jcoplien/trygve/compare/master...mbrowne:trygve:fix-dijkstra?expand=1

...but for some reason, even though the `Node` role is unused (as far as I can tell), if I remove it completely, I get this error:

> Exception in thread "main" java.lang.NullPointerException: Cannot invoke "info.fulloo.trygve.declarations.Type.getText()" because the return value of "info.fulloo.trygve.declarations.Declaration.type()" is null
	at info.fulloo.trygve.declarations.Declaration$MethodSignature.getText(Declaration.java:974)
	at info.fulloo.trygve.parser.Pass1Listener.exitRole_body(Pass1Listener.java:861)
	at info.fulloo.trygve.parser.KantParser$Role_bodyContext.exitRule(KantParser.java:1528)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:62)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:38)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
	at info.fulloo.trygve.parser.ParseRun.pass2(ParseRun.java:151)
	at info.fulloo.trygve.parser.ParseRun.commonInit(ParseRun.java:123)
	at info.fulloo.trygve.parser.ParseRun$BatchParseRun.<init>(ParseRun.java:249)
	at info.fulloo.trygve.editor.BatchRunner.processBatch(BatchRunner.java:42)
	at info.fulloo.trygve.editor.Main.main(Main.java:50)

Am I missing something here, or is this a bug?

I named this issue "possible issue with role re-binding" because I wonder if it has something to do with the fact that roles for Node objects are re-bound multiple times, but I have no idea if that's the case.

**Comment by jcoplien** [comment]
Hi, Matt,

Thanks for the report.

Anything that causes a crash like this is a bug. As a “research quality” environment trygve recovers even from crashes, so in the end it in theory doesn’t matter. In practice I like things tidy.

Your code does have an error, because Node is indeed used at line 65. The compiler gives a reasonable diagnostic, at least for me, before crashing:

￼

The error is therefore somewhere in the compiler’s “stumbling” strategy which it uses to be able to continue to analyze the source for errors even in light of existing errors.

This is now fixed in trygve version 4.4.1.

Thanks for taking the time to report this, Matt!

— Cope

**Comment by mbrowne** [comment]
Great, thanks for the fix. I didn't realize (or perhaps didn't remember) that you can use roles as type annotations for parameters, so that's why I didn't realize that the `Node` role was in fact being referenced. Here's my updated PR to clean up the Dijkstra example:

https://github.com/jcoplien/trygve/pull/139
