### ISSUE TITLE
Assertion error in RTObjectCommon.unenlistAsRolePlayerForContext

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#49]
I have implemented the frontloading example (untested) and it's now parsing, but I'm getting an AssertionError when I run it:

```
//Activity Planning: Frontload Activities
//Use case: http://mbrowne.github.io/prokon-dci/#/use-cases/frontload-activities

context FrontloadActivities
{
    private Project project_;

    public FrontloadActivities(Project proj) {
        project_ = proj;
        Activities = proj.activities();
    }

    public void frontload() {
        Activities.resetStartTimes();
        List<Activity> unplannedActivities;
        do {
            unplannedActivities = Activities.findUnplanned();
            for (int i = 0; i < unplannedActivities.size(); i++) {
                Activity activity = unplannedActivities.get(i);

                //Check to see if early start time has been set.
                //(If the activity has already been planned, then early start time will already be set.)
                if (activity.earlyStartTime() == null) {
                    new FrontloadActivities_PlanActivity(activity)
                        .tryToPlan(project_.startTime());
                }
            }
        }
        while (unplannedActivities.size() > 0);
    }

    role Activities {   
        public void resetStartTimes() {
            for (int i = 0; i < Activities.size(); i++) {
                Activities.get(i).setEarlyStartTime(null);
            }
        }

        public List<Activity> findUnplanned() {
            List<Activity> unplanned = new List<Activity>();
            for (int i = 0; i < Activities.size(); i++) {
                if (Activities.get(i).earlyStartTime() == null) {
                    unplanned.add(Activities.get(i));
                }
            }
            return unplanned;
        }
    }
    requires {
        int size();
        Activity get(int i);
    }
}

///////////////////////////////////////
context FrontloadActivities_PlanActivity
{
    public FrontloadActivities_PlanActivity(Activity activity) {
        UnplannedActivity = activity;
        Predecessors = activity.dependencies();
    }

    public void tryToPlan(int projectStart) {
        if (UnplannedActivity.hasOnlyPlannedPredecessors()) {
            UnplannedActivity.plan(projectStart);
        }
    }

    role Predecessors {
        public int maxEarlyFinishTime(int projectStart) {
            int maxEarlyFinish = projectStart.clone;
            for (int i=0; i < size(); i++) {
                if (Predecessors.get(i).earlyFinishTime() > maxEarlyFinish) {
                    maxEarlyFinish = Predecessors.get(i).earlyFinishTime();
                }
            }
            return maxEarlyFinish;
        }
    }
    requires {
        int size();
        Activity get(int i);
    }

    role UnplannedActivity {
        public boolean hasOnlyPlannedPredecessors() {
            for (int i = 0; i < Predecessors.size(); i++) {
                if (Predecessors.get(i).earlyStartTime() == null) {
                    return false;
                }
            }
            return true;
        }

        public void plan(int projectStart) {
            setEarlyStartTime(Predecessors.maxEarlyFinishTime(projectStart));
        }
    }
    requires {
        List<Activity> dependencies();
        void setEarlyStartTime(int time);
    }
}

///////////////////////////////////////
context Activity {
    private String name_;
    private List<Activity> dependencies_;

    public Activity(String name, int duration, int earlyStartTime) {
        name_ = name.clone;
        Duration = duration;
        EarlyStart = earlyStartTime;
        dependencies_ = new List<Activity>();
    }

    public Activity(String name, int duration, int earlyStartTime, List<Activity> dependencies) {
        //Not supported; copying and pasting for now
        //this(name, duration, earlyStartTime);

        name_ = name.clone;
        Duration = duration;
        EarlyStart = earlyStartTime;

        dependencies_ = dependencies;
    }

    public void addDependency(Activity a) {
        dependencies_.add(a);
    }

    stageprop Duration {} requires {
        int +(int time) const;
    }

    //earliest possible start time for this activity
    stageprop EarlyStart {} requires {
        int +(int duration) const;
    }

    public int earlyFinishTime() {
        return EarlyStart + (Duration + 0);
    }

    public int earlyStartTime() {
        return EarlyStart + 0;
    }

    public void setEarlyStartTime(int time) {
        EarlyStart = time;
    }

    public String name() {
        return name_;
    }

    public int duration() {
        return Duration + 0;
    }

    public List<Activity> dependencies() {
        return dependencies_;
    }
}

///////////////////////////////////////
context Project {
    private int startTime_;
    private List<Activity> activities_;

    public Project(int startTime) {
        startTime_ = startTime.clone;
        activities_ = new List<Activity>();
    }

    public Project(int startTime, List<Activity> activities) {
        startTime_ = startTime.clone;
        activities_ = activities;
    }

    public void addActivity(Activity a) {
        activities_.add(a);
    }

    public void removeActivity(Activity a) {
        activities_.remove(a);
    }

    public int startTime() {
        return startTime_;
    }

    public List<Activity> activities() {
        return activities_;
    }
}

///////////////////////////////////////
{
    Project proj = new Project(0);

    Activity a1 = new Activity("eat breakfast", 2, 0);
    Activity a2 = new Activity("go to the moon", 100, 0);
    a2.addDependency(a1);
    Activity a3 = new Activity("do a moon walk", 5, 0);
    a3.addDependency(a2);
    a3.addDependency(a1);
    Activity a4 = new Activity("read newspaper", 5, 0);

    proj.addActivity(a1);
    proj.addActivity(a2);
    proj.addActivity(a3);
    proj.addActivity(a4);

    new FrontloadActivities(proj).frontload();
}


___________________________________________________________
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
    at info.fulloo.trygve.run_time.RTObjectCommon.unenlistAsRolePlayerForContext(RTObjectCommon.java:160)
    at info.fulloo.trygve.run_time.RTContext$RTContextInfo.removeRolePlayer(RTContext.java:222)
    at info.fulloo.trygve.run_time.RTObjectCommon$RTContextObject.setRoleBinding(RTObjectCommon.java:260)
    at info.fulloo.trygve.run_time.RTExpression$RTAssignment$RTAssignmentPart2.processRoleOrStagePropBinding(RTExpression.java:2156)
    at info.fulloo.trygve.run_time.RTExpression$RTAssignment$RTAssignmentPart2.run(RTExpression.java:2041)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:362)
    at info.fulloo.trygve.run_time.RTExpression$RTMessage.pushArgumentLoop(RTExpression.java:842)
    at info.fulloo.trygve.run_time.RTExpression$RTMessage.run(RTExpression.java:1048)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:362)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.run(RunTimeEnvironment.java:153)
    at info.fulloo.trygve.editor.TextEditorGUI.runButtonActionPerformed(TextEditorGUI.java:590)
    at info.fulloo.trygve.editor.TextEditorGUI$7.actionPerformed(TextEditorGUI.java:216)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6516)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6281)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:699)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:713)
    at java.awt.EventQueue$4.run(EventQueue.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by mbrowne** [comment]
Note: I just made a small edit to the above code listing.

**Comment by jcoplien** [comment]
I think this is fixed. It was that lack of a hashCode and equal function on RTContextObject that we discussed.

**Comment by runefs** [comment]
Meaning that the hashCode implementation is fragile when it comes to identity doesn't it?

Mvh
Rune

**Comment by jcoplien** [comment]
Not reproducible in 1.3.1. Instead, I get the following diagnostic suite. Please re-open if this is inappropriate or if the problem recurs.

And, yes, Rune, you're right. There are _so_ many things broken in the Java library, Full of new surprises every day.

line 84: NONCOMPLIANT: Trying to enact object script `size()' without using the interface of the Role it is playing:`Predecessors'.
line 85: NONCOMPLIANT: Trying to enact object script `get(int)' without using the interface of the Role it is playing:`Predecessors'.

---

line 0: FATAL: TERMINATED: Attempt to invoke script `+' on null object on left-hand side of operation involving`rhs'.

**Comment by jcoplien** [comment]
Closed as indicated above.

**Comment by mbrowne** [comment]
It's working as described, thank you (sorry, I missed your earlier "I think this is fixed" comment).
