### ISSUE TITLE
Initializing property using `new`

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#57]
I noticed that it's possible to use the `new` keyword in a property declaration (i.e. outside the constructor). This compiles but in the below example, I get this error at run-time:

```
line 30: FATAL: TERMINATED: Attempting to invoke method add on a null object
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
```

If this usage is incorrect, then would it be possible to catch it at compile time?

```
class Activity {
    private String name_;
    private int duration_;
    //earliest possible start time for this activity
    private int earlyStart_;
    private List<Activity> dependencies_ = new List<Activity>();

    public Activity(String name, int duration, int earlyStartTime) {
        name_ = name.clone;
        duration_ = duration.clone;
        earlyStart_ = earlyStartTime.clone;
    }

    public Activity(String name, int duration, int earlyStartTime, List<Activity> dependencies) {
        //Not supported; copying and pasting for now
        //this(name, duration, earlyStartTime);

        name_ = name.clone;
        duration_ = duration.clone;
        earlyStart_ = earlyStartTime.clone;

        for (int i=0; i < dependencies.size(); i++) {
            addDependency(dependencies.get(i));
        }
    }

    public void addDependency(Activity activity) {
        //TODO This results in the compiler error "You may not use an object of type 'Activity' as an argument to `!='."
        //assert(activity != this, "An activity cannot have a dependency on itself");
        dependencies_.add(activity);
    }

    public int earlyFinishTime() {
        return earlyStart_ + duration_;
    }

    public int earlyStartTime() {
        return earlyStart_;
    }

    public void setEarlyStartTime(int time) {
        earlyStart_ = time.clone;
    }

    public String name() {
        return name_;
    }

    public int duration() {
        return duration_;
    }

    public List<Activity> dependencies() {
        return dependencies_;
    }
}

{
Activity a1 = new Activity("eat breakfast", 2, 0);
    Activity a2 = new Activity("go to the moon", 100, 0);
    a2.addDependency(a1);
}

___________________________________________________________
line 30: FATAL: TERMINATED: Attempting to invoke method add on a null object
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
    at info.fulloo.trygve.run_time.RTMessageDispatcher$RTNonContextToNonContext.getMethodDecl(RTMessageDispatcher.java:658)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.commonWrapup(RTMessageDispatcher.java:306)
    at info.fulloo.trygve.run_time.RTMessageDispatcher$RTNonContextToNonContext.<init>(RTMessageDispatcher.java:642)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.makeDispatcher(RTMessageDispatcher.java:71)
    at info.fulloo.trygve.run_time.RTExpression$RTMessage.run(RTExpression.java:683)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:362)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.run(RunTimeEnvironment.java:153)
    at info.fulloo.trygve.editor.TextEditorGUI.runButtonActionPerformed(TextEditorGUI.java:590)
    at info.fulloo.trygve.editor.TextEditorGUI$7.actionPerformed(TextEditorGUI.java:216)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6516)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6281)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:699)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:713)
    at java.awt.EventQueue$4.run(EventQueue.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by jcoplien** [comment]
I don’t know what a “property declaration” is.

I’d guess that earlyStart_ was just never given a value.

**Comment by mbrowne** [comment]
I guess that's the wrong term. I was referring to this:

`private List<Activity> dependencies_ = new List<Activity>();`

**Comment by jcoplien** [comment]
Aha. Now I understand — I think... Please try the latest version. Both you and Trygve have tried using this style of initialization. To support it in general would be very difficult, but for now I allow such use to initially bind instance objects to constant values.

**Comment by mbrowne** [comment]
I now get the below output, which I think is a fine compiler error. Minor question: I'm wondering why the error appears so many times.

```
line 6: Improperly formed initialization of dependencies_: non-constant right-hand side `[new List<Activity>]'.
line 6: Improperly formed initialization of dependencies_: non-constant right-hand side `[new List<Activity>]'.
line 6: Improperly formed initialization of dependencies_: non-constant right-hand side `temp$101 = [new List<Activity>]'.
line 6: Improperly formed initialization of dependencies_: non-constant right-hand side `[new List<Activity>]'.
line 6: Improperly formed initialization of dependencies_: non-constant right-hand side `[new List<Activity>]'.
line 6: Improperly formed initialization of dependencies_: non-constant right-hand side `temp$101 = [new List<Activity>]'.
line 6: Improperly formed initialization of dependencies_: non-constant right-hand side `[new List<Activity>]'.
line 6: Improperly formed initialization of dependencies_: non-constant right-hand side `[new List<Activity>]'.
line 6: Improperly formed initialization of dependencies_: non-constant right-hand side `temp$101 = [new List<Activity>]'.
```

**Comment by jcoplien** [comment]
Yes, for the time being, that is correct (though a bit verbose…) To in general call a constructor (as you do by invoking new) from within the scope of a partly initialized object could lead to the use of yet uninitialized objects in that scope. So for now I limit the initializations to constant values.

Getting the multiplicity of error messages reduced is a messy engineering issue. I know the problem and solution, but it’s messy, and isn’t a high priority right now.

**Comment by mbrowne** [comment]
Yes, that makes sense (I was just experimenting, not really expecting it to work given my experience with Java and other languages but curious if it would). Closing this issue now, thanks.

**Comment by jcoplien** [comment]
Thanks.
