### ISSUE TITLE
Chainable methods and Roles

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#59]
Should this work as expected? Especially the `chainMe` return value?

``` java
class Chainable {
    public Chainable() {}

    public Chainable chain() {
        System.out.println("chain");
        return this;
    }
}

context Chainer {
    role Chain {
        public Chain chainMe() {
            return chain();
        }
    } requires {
        Chain chain();
    }

    public Chainer() {
        Chain = new Chainable();
    }

    public Chainer chainIt() {
        Chain.chainMe().chainMe();
        return this;
    }
}

new Chainer().chainIt().chainIt()

/* GOLD:
___________________________________________________________
chain
chain
chain
chain
*/
```

Currently I get this when compiling:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at info.fulloo.trygve.declarations.Type$RoleType.canBeConvertedFrom(Type.java:581)
    at info.fulloo.trygve.parser.Pass1Listener.processReturnExpression(Pass1Listener.java:1708)
    at info.fulloo.trygve.parser.Pass1Listener.exitExpr(Pass1Listener.java:1651)
    at info.fulloo.trygve.parser.KantParser$ExprContext.exitRule(KantParser.java:3069)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at info.fulloo.trygve.parser.ParseRun.pass1(ParseRun.java:99)
    at info.fulloo.trygve.parser.ParseRun.<init>(ParseRun.java:68)
    at info.fulloo.trygve.editor.TextEditorGUI.parseButtonActionPerformed(TextEditorGUI.java:599)
    at info.fulloo.trygve.editor.TextEditorGUI$8.actionPerformed(TextEditorGUI.java:227)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        ...
```

**Comment by ciscoheat** [comment]
It also opens up a discussion whether this style is practical in a DCI application. I'm interested in your thoughts about that.

**Comment by jcoplien** [comment]
1. Fixed.
2. I’m so focused on the compiler these days that I’m out of abstract thinking mode (except for the less subtle issues that Matt raises). Can you tell me more about the subtlety of what’s on your mind?

**Comment by ciscoheat** [comment]
I was curious how to support a chainable API in a Context, similar to the style of some FP libraries, and also considering that Smalltalk does return self as default.

But I'm not so sure how useful it is really in RoleMethods. Since we're mostly asking Role players to do things, `void` gives a cleaner code, doesn't it? I'm happy how clean and simple the spell checker context is now.

Additional experimenting have currently lead me to this:

``` java
class Chainable {
    public Chainable() {}

    public Chainable first() const {
        System.out.println("first");
        return this;
    }

    public Chainable second() const {
        System.out.println("second");
        return this;
    }
}

context FirstLevel {
    stageprop First {
        public First firstOne() {
            first();
            new SecondLevel(this).start();
            return this;
        }
    } requires {
        First first() const;
        // NOTE: Commenting out this crashes when compiling:
//        First second() const;
    }

    public FirstLevel() {
        First = new Chainable();
    }

    public First start() {
        First.firstOne();
        // NOTE: Is returning a RolePlayer allowed?
        return First;
    }
}

context SecondLevel {
    stageprop Second {
        public Second secondOne() {
            second();
            return this;
        }
    } requires {
        Second second() const;
    }

    public SecondLevel(Second second) {
        Second = second;
    }

    public void start() {
        Second.secondOne();
    }
}

(new FirstLevel()).start()

/* GOLD:
___________________________________________________________
first
second
*/
```

Some nested context experiments. It basically works, but should returing a RolePlayer from a Context be allowed?

**Comment by jcoplien** [comment]
> Den 26/01/2016 kl. 15.17 skrev Andreas notifications@github.com:
> 
> I was curious how to support a chainable API in a Context, similar to the style of some FP libraries, and also considering that Smalltalk does return self as default.

This is how System._.print_ works in trygve, btw.

**Comment by jcoplien** [comment]
> Den 26/01/2016 kl. 15.17 skrev Andreas notifications@github.com:
> 
> But I'm not so sure how useful it is really in RoleMethods. Since we're mostly asking Role players to do things, void gives a cleaner code, doesn't it?

Maybe.

I’d be more keen on disallowing parameters to Role methods — a Role should interact only with other Roles.

**Comment by jcoplien** [comment]
line 19: No matching constructor on class `SecondLevel' for`new' invocation

---

> Den 26/01/2016 kl. 15.17 skrev Andreas notifications@github.com:
> 
> class Chainable {
>     public Chainable() {}
> 
> ```
> public Chainable first() const {
>     System.out.println("first");
>     return this;
> }
> 
> public Chainable second() const {
>     System.out.println("second");
>     return this;
> }
> ```
> 
> }
> 
> context FirstLevel {
>     stageprop First {
>         public First firstOne() {
>             first();
>             new SecondLevel(this).start();
>             return this;
>         }
>     } requires {
>         First first() const;
>         // NOTE: Commenting out this crashes when compiling:
> //        First second() const;
>     }
> 
> ```
> public FirstLevel() {
>     First = new Chainable();
> }
> 
> public First start() {
>     First.firstOne();
>     // NOTE: Is returning a RolePlayer allowed?
>     return First;
> }
> ```
> 
> }
> 
> context SecondLevel {
>     stageprop Second {
>         public Second secondOne() {
>             second();
>             return this;
>         }
>     } requires {
>         Second second() const;
>     }
> 
> ```
> public SecondLevel(Second second) {
>     Second = second;
> }
> 
> public void start() {
>     Second.secondOne();
> }
> ```
> 
> }
> 
> (new FirstLevel()).start()

**Comment by ciscoheat** [comment]
That's interesting, I thought it was useful to pass some data around for manipulation, like the current word in the spell checker, and an order that turns into food in the restaurant example. Is the point to encourage creation of highly descriptive Role methods that maps to the use case?

**Comment by ciscoheat** [comment]
I've commented out line 25 to highlight a crash when compiling (no error message):

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at info.fulloo.trygve.declarations.Type$StagePropType.canBeConvertedFrom(Type.java:805)
    at info.fulloo.trygve.declarations.FormalParameterList.alignsWithParameterListIgnoringParamCommon(FormalParameterList.java:112)
    at info.fulloo.trygve.declarations.FormalParameterList.alignsWithUsingConversion(FormalParameterList.java:51)
    at info.fulloo.trygve.semantic_analysis.StaticScope.lookupMethodDeclarationWithConversion(StaticScope.java:1080)
    at info.fulloo.trygve.parser.Pass2Listener.ctorCheck(Pass2Listener.java:534)
    at info.fulloo.trygve.parser.Pass1Listener.newExpr(Pass1Listener.java:4065)
    at info.fulloo.trygve.parser.Pass1Listener.exitAbelian_atom(Pass1Listener.java:2626)
    at info.fulloo.trygve.parser.KantParser$Abelian_atomContext.exitRule(KantParser.java:3521)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at info.fulloo.trygve.parser.ParseRun.pass2(ParseRun.java:103)
    at info.fulloo.trygve.parser.ParseRun.<init>(ParseRun.java:69)
    at info.fulloo.trygve.editor.TextEditorGUI.parseButtonActionPerformed(TextEditorGUI.java:599)
    at info.fulloo.trygve.editor.TextEditorGUI$8.actionPerformed(TextEditorGUI.java:227)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    ...
```

If you remove the comment from line 25 it compiles, but then I'll get a runtime error:

```
___________________________________________________________
first
second
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
    at info.fulloo.trygve.run_time.RTExpression$RTIdentifier.run(RTExpression.java:1098)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:364)
    at info.fulloo.trygve.run_time.RTExpression$RTReturn.run(RTExpression.java:3735)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:364)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.run(RunTimeEnvironment.java:155)
    at info.fulloo.trygve.editor.TextEditorGUI.runButtonActionPerformed(TextEditorGUI.java:594)
    at info.fulloo.trygve.editor.TextEditorGUI$7.actionPerformed(TextEditorGUI.java:220)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
```

**Comment by jcoplien** [comment]
> Den 26/01/2016 kl. 16.42 skrev Andreas notifications@github.com:
> 
> That's interesting, I thought it was useful to pass some data around for manipulation, like the current word in the spell checker

That should be a Role!!!

**Comment by jcoplien** [comment]
Dumb me. Now I understand. And I think I’ve fixed it.

**Comment by ciscoheat** [comment]
If the current word should be a Role, should it be in a nested Context then? Putting it in the same Context as `SpellChecker` and `Dictionary` forces a rebinding of the `Word` role when it changes, or a recursive instantiation of the `SpellCheck` Context, with multiple constructors. Is this code complexity not a problem? I'm experimenting with it, can post another issue.

**Comment by ciscoheat** [comment]
The FirstLevel/SecondLevel code works now, but what about returning a Role player (as in `FirstLevel.start`)? The type seems unusable outside the Context, but shouldn't it at least issue a warning?

**Comment by jcoplien** [comment]
> Den 26/01/2016 kl. 19.08 skrev Andreas notifications@github.com:
> 
> The FirstLevel/SecondLevel code works now, but what about returning a Role player (as in FirstLevel.start)? The type seems unusable outside the Context, but shouldn't it at least issue a warning?

Still thinking about that one...

**Comment by jcoplien** [comment]
> Den 26/01/2016 kl. 19.10 skrev James O Coplien jcoplien@gmail.com:
> 
> > Den 26/01/2016 kl. 19.08 skrev Andreas <notifications@github.com <mailto:notifications@github.com>>:
> > 
> > The FirstLevel/SecondLevel code works now, but what about returning a Role player (as in FirstLevel.start)? The type seems unusable outside the Context, but shouldn't it at least issue a warning?
> 
> Still thinking about that one...

This compiles:

```
 { Object o = (new Chainer()).chainIt().chainIt() }
```

This doesn’t:

```
{ String o = (new Chainer()).chainIt().chainIt() }
```

So, isn’t this as it should be? Is there any way to get in trouble either by returning an object bound to a Role, or by using such an object that is returned?

Interesting!

**Comment by ciscoheat** [comment]
It seems ok, since the runtime will warn about an object playing a Role in multiple Contexts anyway, right? But how about a warning (error even?) if someone tries to return a Role type from a Context? Since it shouldn't be accessible outside the Context.

**Comment by jcoplien** [comment]
My point was that the Role remains inaccessible. That's no reason to make its associated object inaccessible. 

Sendt fra min iPhone

**Comment by ciscoheat** [comment]
Yes, I was just thinking that if someone tries to return a Role explicitly from a Context method should give a warning:

``` java
public SomeRole start() {
    return SomeRole;
}
```

But this should be fine:

``` java
public Object start() {
    return SomeRole;
}
```

**Comment by jcoplien** [comment]
No, I don't think there are any dragons here, and there's no use to warn the user. It's a bit odd but it's not problematic. We want to prevent problems rather than flag innovative use of the language.

**Comment by ciscoheat** [comment]
Ok, sounds good!

**Comment by jcoplien** [comment]
Thanks.

BTW, try out String.join.

**Comment by ciscoheat** [comment]
It's working very well, thank you for that!
