### ISSUE TITLE
AssertionError when using role vector

### ISSUE THREAD

**Issue by mbrowne** [jcoplien/trygve#66]
As discussed on the group, this code produces a run-time error:

```
context C1 {
    public C1(List<AClass> myList) {
        CollectionRole = myList;
    }

    public void trigger() {
        CollectionRole[0].bar();
    }

    role [] CollectionRole {
        public void bar() {
            for (int i=0; i < size(); i++) {
                CollectionRole[i].doBar();
            }
        }

        private void doBar() {}
    }
    requires {
        void foo();
        int size() const;
    }
}

class AClass {
    public void foo() {}
}

{
    new C1(new List<AClass>()).trigger();
}

___________________________________________________________
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
    at info.fulloo.trygve.run_time.RTExpression$RTAssignment$RTAssignmentPart2.run(RTExpression.java:1679)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:372)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.pushArgumentLoop(RTMessageDispatcher.java:255)
    at info.fulloo.trygve.run_time.RTMessageDispatcher$RTNonContextToContext.<init>(RTMessageDispatcher.java:767)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.makeDispatcher(RTMessageDispatcher.java:88)
    at info.fulloo.trygve.run_time.RTExpression$RTMessage.run(RTExpression.java:686)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:372)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.run(RunTimeEnvironment.java:157)
    at info.fulloo.trygve.editor.TextEditorGUI.runButtonActionPerformed(TextEditorGUI.java:594)
    at info.fulloo.trygve.editor.TextEditorGUI$7.actionPerformed(TextEditorGUI.java:220)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6516)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6281)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:699)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:713)
    at java.awt.EventQueue$4.run(EventQueue.java:711)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

The same error occurs with a non-empty list, e.g.:

```
List<AClass> list = new List<AClass>();
list.add(new AClass());
new C1(list).trigger();
```

**Comment by jcoplien** [comment]
Fixed in 1.4.5 push.

**Comment by mbrowne** [comment]
Thanks, but it's still giving a runtime error with the non-empty list test:

```
List<AClass> list = new List<AClass>();
list.add(new AClass());
new C1(list).trigger();
```

```
___________________________________________________________
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
    at info.fulloo.trygve.run_time.RTMessageDispatcher.genericPolymorphicMethodLookup(RTMessageDispatcher.java:549)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.genericMethodDeclLookup(RTMessageDispatcher.java:626)
    at info.fulloo.trygve.run_time.RTMessageDispatcher$RTRoleToRole.getMethodDecl(RTMessageDispatcher.java:1189)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.commonWrapup(RTMessageDispatcher.java:334)
    at info.fulloo.trygve.run_time.RTMessageDispatcher$RTRoleToRole.<init>(RTMessageDispatcher.java:1171)
    at info.fulloo.trygve.run_time.RTMessageDispatcher.makeDispatcher(RTMessageDispatcher.java:120)
    at info.fulloo.trygve.run_time.RTExpression$RTMessage.run(RTExpression.java:690)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:372)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.run(RunTimeEnvironment.java:157)
    at info.fulloo.trygve.editor.TextEditorGUI.runButtonActionPerformed(TextEditorGUI.java:594)
    at info.fulloo.trygve.editor.TextEditorGUI$7.actionPerformed(TextEditorGUI.java:220)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jcoplien** [comment]
Full code listing?

**Comment by mbrowne** [comment]
Same as above, only difference is the main expression. Here it is all together:

```
context C1 {
    public C1(List<AClass> myList) {
        CollectionRole = myList;
    }

    public void trigger() {
        CollectionRole[0].bar();
    }

    role [] CollectionRole {
        public void bar() {
            for (int i=0; i < size(); i++) {
                CollectionRole[i].doBar();
            }
        }

        private void doBar() {}
    }
    requires {
        void foo();
        int size() const;
    }
}

class AClass {
    public void foo() {}
}

{
    List<AClass> list = new List<AClass>();
    list.add(new AClass());
    new C1(list).trigger();
}
```

**Comment by jcoplien** [comment]
> Den 07/02/2016 kl. 23.36 skrev Matt Browne notifications@github.com:
> 
> Same as above, only difference is the main expression. Here it is all together:

The code is badly wrong. I’m working on generating a suitable diagnostic.

**Comment by jcoplien** [comment]
Please try the new version.

> Den 07/02/2016 kl. 23.37 skrev James O Coplien jcoplien@gmail.com:
> 
> > Den 07/02/2016 kl. 23.36 skrev Matt Browne <notifications@github.com <mailto:notifications@github.com>>:
> > 
> > Same as above, only difference is the main expression. Here it is all together:
> 
> The code is badly wrong. I’m working on generating a suitable diagnostic.

**Comment by mbrowne** [comment]
It now produces a suitable error message:

```
line 3: Roles in `CollectionRole' cannot be played by objects of type `AClass':
line 3:     `size' needed by Role `CollectionRole' does not appear in interface of `AClass'.
```

I got off on the wrong track because I misunderstood your earlier example (my fault). (Interesting way of looping, BTW, although I'm not sure it's as beginner-friendly as a for or foreach loop would be.)

I'm still getting a NullPointerException when trying to compile the example you posted on the group. I could file a new issue for this but I'll just mention it here for now:

```
context C1 {
    public C1(List<AClass> myList) {
        CollectionRole = myList;
    }

    public void trigger() {
        CollectionRole[0].bar();
    }

    role [] CollectionRole {
        public void bar() {
           doBar();
           if (index < size() - 1) {
              CollectionRole[index + 1].bar()
           }
        }
        private void doBar() {}
    }
    requires {
        void foo();
        int size() const;
    }
}

class AClass {
    public void foo() {}
}

{
    List<AClass> list = new List<AClass>();
    list.add(new AClass());
    new C1(list).trigger();
}
```

```
___________________________________________________________
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at info.fulloo.trygve.expressions.Expression$IfExpression.<init>(Expression.java:805)
    at info.fulloo.trygve.parser.Pass1Listener.exitIf_expr(Pass1Listener.java:3237)
    at info.fulloo.trygve.parser.KantParser$If_exprContext.exitRule(KantParser.java:4645)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at info.fulloo.trygve.parser.ParseRun.pass1(ParseRun.java:99)
    at info.fulloo.trygve.parser.ParseRun.<init>(ParseRun.java:68)
    at info.fulloo.trygve.editor.TextEditorGUI.parseButtonActionPerformed(TextEditorGUI.java:599)
    at info.fulloo.trygve.editor.TextEditorGUI$8.actionPerformed(TextEditorGUI.java:227)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jcoplien** [comment]
> Den 08/02/2016 kl. 00.48 skrev Matt Browne notifications@github.com:
> 
> (Interesting way of looping, BTW, although I'm not sure it's as beginner-friendly as a for or foreach loop would be.)
> 
> It’s the object-oriented way of doing things. You need to focus on what objects individually can do to contribute to the whole. Think of it as generating emergent behaviour.

I’ll bet it’s even more intuitive for a 7-year-old than looping is. I think you’re still working on the paradigm shift.

If any single, contiguous block of code knows about more than two objects, it’s likely that global, procedural thinking is at play. Tease out the respective intelligence of the individual Roles and distribute it accordingly. In general, you end with code that is much more cohesive. It’s probably a coin toss in this case, but it’s good to keep in practice ;-)

> I'm still getting a NullPointerException when trying to compile the example you posted on the group. I could file a new issue for this but I'll just mention it here for now:
> 
> This will be gone in the next push. (And you also should be able to go back to Java 7).

**Comment by mbrowne** [comment]
It looks like it's working as intended now, assuming it's supposed to give this compile error:

```
line 3: Roles in `CollectionRole' cannot be played by objects of type `AClass':
line 3:     `size' needed by Role `CollectionRole' does not appear in interface of `AClass'.
```

I'm closing the issue, but I'm wondering how you intended for the CollectionRole to access its size(), since size() is a method of List, not a method of AClass.

Also, I thought I'd mention an alternative approach:

```
context C1 {
    public C1(List<AClass> myList) {
        CollectionRole = myList;
    }

    public void trigger() {
        CollectionRole.bar();
    }

    role CollectionRole {
        public void bar() {
            for (int i=0; i < CollectionRole.size(); i++) {
                doBar();
            }
        }

        private void doBar() {}
    }
    requires {
        int size() const;
    }
}
```

It depends on the mental model whether it makes more sense to bind the collection as a whole to a role, or to bind each of its items to a role. I think either approach is an improvement over my original version because they both give responsibility to the role rather than putting it in a Context script.

**Comment by jcoplien** [comment]
> Den 08/02/2016 kl. 14.06 skrev Matt Browne notifications@github.com:
> 
> It looks like it's working as intended now, assuming it's supposed to give this compile error:
> 
> line 3: Roles in `CollectionRole' cannot be played by objects of type`AClass':
> line 3:     `size' needed by Role`CollectionRole' does not appear in interface of `AClass’.
> That’s correct.
> 
> I'm closing the issue, but I'm wondering how you intended for the CollectionRole to access its size(), since size() is a method of List, not a method of AClass.
> 
> The code I sent you via Email was a quick edit of the code you sent me, and the size() invocation shouldn’t have been there. Instead, the sequencing should have been orchestrated with index and lastIndex.

I am working on a Spell Checker example that works that way.

> Also, I thought I'd mention an alternative approach:
> 
> context C1 {
>     public C1(List<AClass> myList) {
>         CollectionRole = myList;
>     }
> 
> ```
> public void trigger() {
>     CollectionRole.bar();
> }
> 
> role CollectionRole {
>     public void bar() {
>         for (int i=0; i < CollectionRole.size(); i++) {
>             doBar();
>         }
>     }
> 
>     private void doBar() {}
> }
> requires {
>     int size() const;
> }
> ```
> 
> }
> It depends on the mental model whether it makes more sense to bind the collection as a whole to a role, or to bind each of its items to a role. I think either approach is an improvement over my original version because they both give responsibility to the role rather than putting it in a Context script.
> 
> I can’t see any case where a Collection itself has the wherewithal to iterate over its members and to perform any operation on them, other than those things germane to a collection (e.g., tree balancing). It would look really funny in the use case. At best it would be a nested Context (which now works).

**Comment by jcoplien** [comment]
Thanks, Matt.
