### ISSUE TITLE
Stacking input between sessions possible

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#73]
``` java
{
  System.out.print("> ");
  Scanner newScanner = new Scanner(System.in);
  String s = newScanner.nextLine();
  System.out.println(s)
}
```
1. Parse and Run
2. Type anything except Enter, and press Run
3. Type anything and press Enter

```
> 123> 456
line 0: RUNTIME: Unknown run-time error around source line 0 associated with `ret$val'. Check other error messages.
```

**Comment by ciscoheat** [comment]
Still have the same problem after this commit.

**Comment by ciscoheat** [comment]
Still same problem, but now the input doubles on the second run. (I typed 123 on both executions)

```
___________________________________________________________
> 123> 112233

123
line , s.length()=03: RUNTIME: Unknown run-time error around source line 0 associated with `ret$val'. Check other error messages.
```

**Comment by ciscoheat** [comment]
It's not stacking anymore, but try clicking the Run button 10 times or more. Then the `>` stops displaying, and the input is buffered in a very strange way. Sometimes it finishes when you press Enter and starts the next program execution, other times not. Interrupting won't help either, the next Run has the same behavior.

**Comment by jcoplien** [comment]
I cannot reproduce this in 1.5.15. I made a lot of changes to the task environment as a foundation for introducing graphics, and maybe that cleaned it up.

**Comment by ciscoheat** [comment]
Yes, it has improved, when clicking run multiple times now when waiting for input, I get this:

```
> Feb 29, 2016 3:31:46 PM info.fulloo.trygve.editor.MessageConsole$DocInputStream read
SEVERE: null
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
    at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
    at info.fulloo.trygve.editor.MessageConsole$DocInputStream.read(MessageConsole.java:381)
    at info.fulloo.trygve.editor.MessageConsole$DocInputStream.read(MessageConsole.java:405)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:100)
    at java.util.Scanner.readInput(Scanner.java:804)
    at java.util.Scanner.findWithinHorizon(Scanner.java:1685)
    at java.util.Scanner.nextLine(Scanner.java:1538)
    at info.fulloo.trygve.add_ons.ScannerClass$RTNextLineCode.runDetails(ScannerClass.java:143)
    at info.fulloo.trygve.add_ons.ScannerClass$RTScannerCommon.run(ScannerClass.java:116)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:379)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.run(RunTimeEnvironment.java:164)
    at info.fulloo.trygve.editor.TextEditorGUI.simpleRun(TextEditorGUI.java:689)
    at info.fulloo.trygve.editor.TextEditorGUI$29.doInBackground(TextEditorGUI.java:744)
    at info.fulloo.trygve.editor.TextEditorGUI$29.doInBackground(TextEditorGUI.java:738)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

And no matter how many times I press run, it only processes one input.

**Comment by jcoplien** [comment]
What’s happening is that trying to run the app again results in a request to kill the one already running. It does so, successfully — and then starts up the new one.

I agree that the Java stack trace is annoying and will try to print something more suitable.

**Comment by ciscoheat** [comment]
Looks better now!

**Comment by jcoplien** [comment]
Great!  Thanks, Andreas!
