### ISSUE TITLE
Parser error when referencing own Role inside switch

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#74]
``` java
context BorrowLibraryItems {
    role Screen {
        public void displayRemoveLibraryCard() {
            println("Don't forget your library card!");
        }

        public void selectOptions() {
            String choice = "3";
            switch(choice) {
                case "3":
                    // NOTE: Using "Screen" here won't compile, parser error.
                    Screen.displayRemoveLibraryCard();
            }
        }
    } requires {
        void print(String text);
        void println(String text);
    }

    public BorrowLibraryItems() {
        System.out.println("Created.");

        Screen = System.out;
        Screen.selectOptions();
    }
}

new BorrowLibraryItems()

/* GOLD:
___________________________________________________________
Created.
Don't forget your library card!
*/
```

When parsing, this happens:

```
___________________________________________________________
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
    at info.fulloo.trygve.parser.Pass1Listener.isInsideMethodDeclaration(Pass1Listener.java:4878)
    at info.fulloo.trygve.parser.Pass1Listener.idExpr(Pass1Listener.java:4793)
    at info.fulloo.trygve.parser.Pass1Listener.exitAbelian_atom(Pass1Listener.java:2869)
    at info.fulloo.trygve.parser.KantParser$Abelian_atomContext.exitRule(KantParser.java:3762)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
    at info.fulloo.trygve.parser.ParseRun.pass1(ParseRun.java:98)
    at info.fulloo.trygve.parser.ParseRun.<init>(ParseRun.java:67)
    at info.fulloo.trygve.editor.TextEditorGUI.parseButtonActionPerformed(TextEditorGUI.java:636)
    at info.fulloo.trygve.editor.TextEditorGUI$8.actionPerformed(TextEditorGUI.java:237)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    ...
```

**Comment by ciscoheat** [comment]
It seems like this error is preserved in the environment, when opening another file and parsing it, I get this:

```
___________________________________________________________
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at info.fulloo.trygve.run_time.RunTimeEnvironment.reboot(RunTimeEnvironment.java:85)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.<init>(RunTimeEnvironment.java:70)
    at info.fulloo.trygve.code_generation.InterpretiveCodeGenerator.<init>(InterpretiveCodeGenerator.java:130)
    at info.fulloo.trygve.parser.ParseRun.generateCode(ParseRun.java:115)
    at info.fulloo.trygve.parser.ParseRun.<init>(ParseRun.java:74)
    at info.fulloo.trygve.editor.TextEditorGUI.parseButtonActionPerformed(TextEditorGUI.java:656)
    at info.fulloo.trygve.editor.TextEditorGUI$9.actionPerformed(TextEditorGUI.java:246)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    ...
```

**Comment by ciscoheat** [comment]
Not even restarting trygve makes it go away, I get the same error now for any file I try to parse.

**Comment by jcoplien** [comment]
I pushed the wrong version of the source. Try again — this should be better ;-)

> Den 14/02/2016 kl. 17.23 skrev Andreas <notifications@github.com <mailto:notifications@github.com>>:
> 
> Not even restarting trygve makes it go away, I get the same error now for any file I try to parse.

**Comment by ciscoheat** [comment]
Works now, that was fast. :)
