### ISSUE TITLE
Code crashes after running twice

### ISSUE THREAD

**Issue by ciscoheat** [jcoplien/trygve#9]
Open this file in trygve: https://raw.githubusercontent.com/ciscoheat/trygve/examples/examples/chord_identifier.k

Parse and run. It should show

```
C
Chord::notes
3
```

Now run again with no changes. It crashes for me:

```
Exception in thread "AWT-EventQueue-0" java.lang.AssertionError
    at info.fulloo.trygve.run_time.RTObjectCommon.unenlistAsRolePlayerForContext(RTObjectCommon.java:144)
    at info.fulloo.trygve.run_time.RTContext$RTContextInfo.removeAllRolePlayers(RTContext.java:192)
    at info.fulloo.trygve.run_time.RTObjectCommon$RTContextObject.decrementReferenceCount(RTObjectCommon.java:302)
    at info.fulloo.trygve.run_time.RTExpression.setLastExpressionResult(RTExpression.java:3757)
    at info.fulloo.trygve.run_time.RTExpression$RTNew.run(RTExpression.java:2084)
    at info.fulloo.trygve.run_time.RTExpression$RTAssignment.run(RTExpression.java:1630)
    at info.fulloo.trygve.run_time.RTExpression$RTExpressionList.run(RTExpression.java:2986)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.run(RunTimeEnvironment.java:127)
    at info.fulloo.trygve.editor.TextEditorGUI.runButtonActionPerformed(TextEditorGUI.java:590)
    at info.fulloo.trygve.editor.TextEditorGUI$7.actionPerformed(TextEditorGUI.java:221)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6527)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6292)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4883)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4705)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4705)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:719)
    at java.awt.EventQueue$4.run(EventQueue.java:717)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ciscoheat** [comment]
I've minimized the example, the same thing happens with this:

``` java
context Chord {
    stageprop RootTest {} requires {
        double position() const;
    }

    public Chord() {
        System.out.println("Chord::constructor");
    }
}

{
    Chord chord = new Chord();
}
```

**Comment by jcoplien** [comment]
This runs on my latest version — not sure what was happening before.

Also fixed a bug in the scanner that was causing it to read 10.0 like 10 (or 120.0 like 120 — anything with a zero right before the decimal point…)

Also fixed your playing-multiple-roles bug. That was a stickler!

Also seem to have assertions working — with line numbers! That was a bit of a challenge but all in all some good, fun engineering work.
‘
Time for bed.

> Den 17/12/2015 kl. 22.32 skrev Andreas notifications@github.com:
> 
> context Chord {
>     stageprop RootTest {} requires {
>         double position() const;
>     }
> 
> ```
> public Chord() {
>     System.out.println("Chord::constructor");
> }
> ```
> 
> }
> 
> {
>     Chord chord = new Chord();
> }

**Comment by ciscoheat** [comment]
Wonderful, thank you! Everything seems to work very well now. Is it ok if I make a pull request when I update the tests I'm writing?

**Comment by ciscoheat** [comment]
I'm back again. :) Here's the next version, with notes: https://raw.githubusercontent.com/ciscoheat/trygve/examples/examples/chord_identifier.k

I started to explore duck typing, but ran into trouble quite fast. Very exciting feature though!

**Comment by ciscoheat** [comment]
I've updated the url with more issues: https://raw.githubusercontent.com/ciscoheat/trygve/examples/examples/chord_identifier.k

Just search for `NOTE:` and you'll find them. Let me know if I should isolate some of them. 

The example is almost done now, it is very enjoyable to code in trygve.

**Comment by jcoplien** [comment]
Knocking them off one at a time.

Fixed this one:

```
// This one compiles but crashes
// operator problem? 

 assert(l == "A" || l == "B", "Only A or B allowed actually"); 
```

Pretty fundamental error in the run-time machine processing of simple boolean expressions… Thanks.

On to the next…
