### ISSUE TITLE
List<T>.indexOf(T element) runtime error

### ISSUE THREAD

**Issue by hvaldecantos** [jcoplien/trygve#98]
The following code compiles:

``` trygve
class Element {
}
{
    List<Element> elements = new List<Element>()
    Element e1 = new Element()

    elements.add(e1)
    int i = elements.indexOf(e1)
    System.out.println(i)
}
```

But, when invoking `indexOf` the code stops running:

```
Compilation complete
Exception in thread "main" java.lang.ClassCastException: info.fulloo.trygve.run_time.RTObjectCommon cannot be cast to info.fulloo.trygve.run_time.RTObjectCommon$RTIntegerObject
    at info.fulloo.trygve.add_ons.ListClass$RTIndexOfCode.runDetails(ListClass.java:343)
    at info.fulloo.trygve.add_ons.ListClass$RTListCommon.run(ListClass.java:204)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.runner(RunTimeEnvironment.java:381)
    at info.fulloo.trygve.run_time.RunTimeEnvironment.run(RunTimeEnvironment.java:172)
    at info.fulloo.trygve.editor.BatchRunner.simpleRun(BatchRunner.java:61)
    at info.fulloo.trygve.editor.BatchRunner.processBatch(BatchRunner.java:49)
    at info.fulloo.trygve.editor.Main.main(Main.java:34)
```

**Comment by jcoplien** [comment]
Fixed in 1.6.11

**Comment by hvaldecantos** [comment]
Thanks!

**Comment by jcoplien** [comment]
Thanks, Héctor.

Sorry for all these niggling problems. But we’re getting there.

I owe you a response on the training. Soon. It’s in my head but will take a while to write.
